name: command
on: [push]
jobs:
  command:
    name: check the python script
    runs-on: ubuntu-latest
    steps:
      - name: download
        run: wget -O /home/runner/work/Coreform_Cubit_Python_API/Coreform_Cubit_Python_API https://f002.backblazeb2.com/file/cubit-downloads/Coreform-Cubit/Releases/Linux/Coreform-Cubit-2023.11%2B43088-Lin64.tar.gz

